require 'Items/SuburbsDistributions'
require "Items/ProceduralDistributions"

table.insert(SuburbsDistributions["all"]["inventorymale"].items, "WartegFoodExtended.Indomie_Original");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.01);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "WartegFoodExtended.Indomie_Original");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.01);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "WartegFoodExtended.MieSedaap_Goreng");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.01);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "WartegFoodExtended.MieSedaap_Goreng");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.01);

table.insert(SuburbsDistributions["Bag_SurvivorBag"].items, "WartegFoodExtended.Indomie_Original");
table.insert(SuburbsDistributions["Bag_SurvivorBag"].items, 1);
table.insert(SuburbsDistributions["Bag_SurvivorBag"].items, "WartegFoodExtended.MieSedaap_Goreng");
table.insert(SuburbsDistributions["Bag_SurvivorBag"].items, 1);

table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "WartegFoodExtended.Indomie_Original");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, 1);
table.insert(ProceduralDistributions["list"]["KitchenDryFood"].items, "WartegFoodExtended.Indomie_Original");
table.insert(ProceduralDistributions["list"]["KitchenDryFood"].items, 2);
table.insert(ProceduralDistributions["list"]["GigamartDryGoods"].items, "WartegFoodExtended.Indomie_Original");
table.insert(ProceduralDistributions["list"]["GigamartDryGoods"].items, 1);
table.insert(ProceduralDistributions["list"]["CrateRice"].items, "WartegFoodExtended.Indomie_Original");
table.insert(ProceduralDistributions["list"]["CrateRice"].items, 1);
table.insert(ProceduralDistributions["list"]["GasStorageCombo"].items, "WartegFoodExtended.Indomie_Original");
table.insert(ProceduralDistributions["list"]["GasStorageCombo"].items, 2);
table.insert(ProceduralDistributions["list"]["StoreShelfCombo"].items, "WartegFoodExtended.Indomie_Original");
table.insert(ProceduralDistributions["list"]["StoreShelfCombo"].items, 2);
table.insert(ProceduralDistributions["list"]["StoreKitchenPots"].items, "WartegFoodExtended.Indomie_Original");
table.insert(ProceduralDistributions["list"]["StoreKitchenPots"].items, 1);
table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, "WartegFoodExtended.Indomie_Original");
table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, 1);
table.insert(ProceduralDistributions["list"]["KitchenCannedFood"].items, "WartegFoodExtended.Indomie_Original");
table.insert(ProceduralDistributions["list"]["KitchenCannedFood"].items, 2);
table.insert(ProceduralDistributions["list"]["CrateDishes"].items, "WartegFoodExtended.Indomie_Original");
table.insert(ProceduralDistributions["list"]["CrateDishes"].items, 1);

table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "WartegFoodExtended.MieSedaap_Goreng");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, 1);
table.insert(ProceduralDistributions["list"]["KitchenDryFood"].items, "WartegFoodExtended.MieSedaap_Goreng");
table.insert(ProceduralDistributions["list"]["KitchenDryFood"].items, 2);
table.insert(ProceduralDistributions["list"]["GigamartDryGoods"].items, "WartegFoodExtended.MieSedaap_Goreng");
table.insert(ProceduralDistributions["list"]["GigamartDryGoods"].items, 1);
table.insert(ProceduralDistributions["list"]["CrateRice"].items, "WartegFoodExtended.MieSedaap_Goreng");
table.insert(ProceduralDistributions["list"]["CrateRice"].items, 1);
table.insert(ProceduralDistributions["list"]["GasStorageCombo"].items, "WartegFoodExtended.MieSedaap_Goreng");
table.insert(ProceduralDistributions["list"]["GasStorageCombo"].items, 2);
table.insert(ProceduralDistributions["list"]["StoreShelfCombo"].items, "WartegFoodExtended.MieSedaap_Goreng");
table.insert(ProceduralDistributions["list"]["StoreShelfCombo"].items, 2);
table.insert(ProceduralDistributions["list"]["StoreKitchenPots"].items, "WartegFoodExtended.MieSedaap_Goreng");
table.insert(ProceduralDistributions["list"]["StoreKitchenPots"].items, 1);
table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, "WartegFoodExtended.MieSedaap_Goreng");
table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, 1);
table.insert(ProceduralDistributions["list"]["KitchenCannedFood"].items, "WartegFoodExtended.MieSedaap_Goreng");
table.insert(ProceduralDistributions["list"]["KitchenCannedFood"].items, 2);
table.insert(ProceduralDistributions["list"]["CrateDishes"].items, "WartegFoodExtended.MieSedaap_Goreng");
table.insert(ProceduralDistributions["list"]["CrateDishes"].items, 1);